/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/**/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/
*
* Project: Rishi CDA
* Topic: Blood Cultures
* Author: Jennifer Cano
* Date Created: 2/28/23
*
* Description: Pulled blood culture data from Microbiology domain and linked to CPRS orders in 'Pulling Blood Cultures_20230403.sql'
* saved in 'path name'. In this SAS program, will clean blood cultures based on values of Topography/CollectionSample 
* and OrderableItemName PI decied to exclude.
*
/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/**/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/;

libname coh 'path name';
libname bc 'path name';


*create copy of main HAPPI data set;
proc import datafile='path name'
out=coh.happi_20132018_20211029
dbms=dta replace;
run;
/*NOTE: The import data set has 8,095,111 observations and 127 variables.*/


*create variable of day prior to ed arrival;
data coh.happi_20132018_20211029;
set coh.happi_20132018_20211029 ;
format ed_arrival_date_dayprior MMDDYY10.;
ed_arrival_date_dayprior = ed_arrival_date-1;
run;


*create a dflt table of the cohort to use in CDW;
data DFT.happi_20132018_20230403_JC;
set coh.happi_20132018_20211029;
keep patienticn patientsid unique_hosp_count_id new_admitdate3 new_dischargedate3 ed_arrival_date ed_arrival_date_dayprior sta6a sta3n;
run;

*Pulled blood cultures in 'Pulling Blood Cultures_20230403.sql'
* saved in 'path name';
*data set is dflt.HAPPI_BC_CPRS_Micro_JC_20230403;


*import dflt table;
data bc;
set DFT.HAPPI_BC_CPRS_Micro_JC_20230403;
run;
/*NOTE: The data set WORK.BC has 1440274 observations and 25 variables.*/

*are there any specimentakendate missing - no;
proc sql;
select count(distinct unique_hosp_count_id)
from bc
where specimentakendate = .;
quit;

*3/27/23 PI adjudicated which Topography/CollectionSample and OrderableItemName values to drop;
data bc_v2;
set bc;
	if topography = 'BLOOD' and collectionsample in ('TISSUE','WOUND','DONOR BLOOD BAG','BIOPSY',
'ABSCESS','TRANS-BAG','BAG','FLUID  (STERILE CONTAINER)','SWAB','ASPIRATE','ASPIRATE, SPFY','TRANSFUSION UNIT'
'BLOOD PRODUCTS') then delete;
	if topography = 'BLOOD, OTHER CELLS' and collectionsample = 'HEMATOMA' then delete;
	if topography = 'BLOOD, RED BLOOD CELLS(PRBC)' and collectionsample = 'BAG, BLOOD COMPONENT' then delete;
	if topography = 'CSF + RED TOP SERUM' and collectionsample = 'FLUID' then delete;
	if topography = 'PLASMA' and collectionsample = 'Urine' then delete;
	if topography = 'SERUM' and collectionsample in ('SWAB','WOUND') then delete;
	if topography = 'SERUM & CSF' and collectionsample=	'RED TOP & CSF' then delete;
*4/7/23 - additional ones after expanding to HAPPI data set;
	if topography = '1 HOUR BLOOD' and collectionsample= 'SWAB' then delete;
	if topography = 'BLOOD' and collectionsample in ('URINE(MICRO)','UNIT (BLOOD BANK)',
	'TRANSTRACHEAL ASPIRATE','STONE(CALCULUS)','TRANSFUSION REACTION BLOOD','RECTAL SWAB',
	'FLUID, BODY','BONE MARROW (ASPIRATE)','PERITONEAL FLUID','SLIDE','ENTEROBACTERIACEAE SLANT',
	'SALINE (ON SWAB)','PLATELETS','SYRINGE','WOUND/ABSCESS','TRANSFUSION BAG','BONE','SPUTUM',
	'BODY FLUIDS','HEMATOMA','BLOOD BANK UNIT') then delete;
	if topography = 'BLOOD CLOT' and collectionsample= 'TISSUE' then delete;
	if topography = 'BLOOD CLOT, ORGANIZING' and collectionsample='EXUDATE' then delete;
	if topography = 'BLOOD CULTURE' and collectionsample= 'PERITONEAL FLUID' then delete;
	if topography = 'BLOOD CULTURE BOTTLE' and collectionsample= 'WOUND' then delete;
	if topography = 'BLOOD DONOR BAG' and collectionsample= 'BLOOD DONOR BAG' then delete;
	if topography = 'BLOOD VESSEL' and collectionsample= 'SWAB' then delete;
	if topography = 'BLOOD, OTHER CELLS' and collectionsample in ('TISSUE','SWAB') then delete;
	if topography = 'CSF & SERUM' and collectionsample in ('ASPIRATE','FLUID','CSF AND SERUM','URINE(MICRO)') then delete;
	if topography = 'CSF AND SERUM' and collectionsample= 'FLUID' then delete;
	if topography = 'SERUM' and collectionsample in ('WOUND,AEROBIC SWAB','ABSCESS','SPUTUM','DRAINAGE','ZZZFECES','ASPIRATE') then delete;
	if topography = 'URINE & BLOOD' and collectionsample= 'URINE & BLOOD (DO NOT USE)' then delete;


	if orderableitemname in ('AFB CULTURE & FLUOROCHROME SMEAR (OTHER)','AFB CULTURE & SMEAR (NON BLOOD)',
'AFB CULTURE & SMEAR (NON-BLOOD)','AFB CULTURE & SMEAR (NON-BLOOD)-Q',"CBC","CMV (PCR)",
"CMV DNA, QUALITATIVE-BLOOD","COCCIDIOIDES AB, QUANTITATIVE,DID","CRYPTOCOCCAL ANTIGEN",
"CRYPTOCOCCAL ANTIGEN (AL/SY/CN/BH)","CRYPTOCOCCAL ANTIGEN (SERUM)",
"CRYPTOCOCCAL ANTIGEN-KC ","CRYPTOCOCCUS ANTIGEN","CRYPTOCOCCUS ANTIGEN TEST","CRYPTOCOCCUS ANTIGEN-SERUM",
'CULTURE & SUSCEPTIBILITY (NOT BLOOD)',"CULTURE (NOT BLD,UR,STOOL)","CULTURE, ASPIRATE",
"EHRLICHIA SMEAR","FUNGAL SEROLOGY","HELICOBACTER PYLORI AB(disc'd 092016)","HERPES SIMPLEX CSF,DNA PCR(D/C,9/14/20)",
"HERPES SIMPLEX VIRUS CULTURE","HISTOPLASMA AB","HISTOPLASMA ANTIGENS","HSV (PCR)",
'HSV 1&2 PCR QUALITATIVE',"INDIA INK PREP","LEGIONELLA DFA","M CHIMAERA CULT-BLOOD SET 1",
"M CHIMAERA CULT-BLOOD SET 2","M CHIMAERA CULTURE ISOLATOR","MALARIA PREP (NA)","MALARIA SMEAR",
"MALARIA STAIN","MIC/MBC","PARASITE EXAM","PARASITE EXAM, BLOOD (DC'D)","PARASITIC SEROLOGY",
"PARVOVIRUS, HUMAN BY PCR","PCR PARVOVIRUS","POTASSIUM CHLORIDE *HIGH-ALERT* INJ,SOLN ",
'PROCALCITONIN S&W','ROUTINE C&S (NO BLOOD OR STOOL)',"ROUTINE CULTURE/NOT BLOOD OR URINE",
"SEND OUT (MICROBIOLOGY)","SUBCULTURE GRAM STAIN","SUSCEPTIBILITY BETA-LACTAMASE",
"SUSCEPTIBILITY BETA-LACTAMASE X2","SUSCEPTIBILITY E-TEST","SUSCEPTIBILITY E-TEST X2",
"SUSCEPTIBILITY KIRBY-BAUER","SUSCEPTIBILITY KIRBY-BAUER X2","SUSCEPTIBILITY MIC",
"SUSCEPTIBILITY TEST","SUSCEPTIBILITY TESTING 1 (VITEK)","TB T-SPOT (Dc'd 8/2016)",'TISSUE C&S/SMEAR (BU)',
"TRANSFUSED UNIT CULTURE W/GRAM ST",'TYPE & SCREEN',"UM-FUNGUS CULTURE,BLOOD",
"UMMI-MISCELLANEOUS MICROBIOLOGY (M LABS)","VARICELLA-ZOSTER DFA","VIRAL ANTIGENEMIA (DC'D 7/27/17)",
"VIRAL CULTURE","VIRAL CULTURE COMPREHENSIVE","VIRAL CULTURE*NE","VIRAL CULTURE, CMV","VIRAL CULTURE, GENERAL",
"VIRUS ISOLATION","VRE SCREEN","WNV EIA,IGM(NDDH) Dc'd 10/2019 ","WOUND CULTURE PANEL","XPERT MRSA/SA BC PCR ASSAY",
"ZZANTI ENA(Ended 1-25-18)","ZZFUNGAL SEROLOGY","ZZYERSINIA ANTIBODIES IGA, IGM, IGG") then delete;
*4/7/23 - additional ones after expanding to HAPPI data set;
if orderableitemname in ('_CRYPTOSPORIDIUM','AFB (TB) CULTURE & SMEAR ','AFB CULT & SMEAR','AFB CULT/SMEAR RFLX(7148)',
'AFB CULTURE & SMEAR (60152)','AFB CULTURE & SMEAR (SY/BH/CN/BU)','AFB CULTURE & SUSCEPTIBILITIES','AFB CULTURE (QUEST)',
'AFB CULTURE&SMEAR(O)','AFB CULTURE/SMEAR','AFB FLUIDS CULTURE & SMEAR','AFB SMEAR & CULTURE (LABCORP)','AFB SMEAR*','ANAEROBE IDENTIFICATION',
'BARTONELLA (ROCHALIMAEA) CULTURE','BASIC METABOLIC PANEL',"BLASTOMYCES AG(Dc'd 9/2019)",'BLOOD PARASITE EXAM (BU/BH)',
'BLOOD PARASITES','BLOOD PRODUCT CULTURE','BODY FLUID','BONE MARROW BACTERIAL CULTURE','BONE MARROW FUNGUS CULTURE',
'BORDETELLA PERTUSSIS AG, PCR','BRUCELLA CULTURE, BLOOD','C&S AND SMEAR-WOUND','C&S-WOUND','CEFTRIAXONE INJ,SOLN ',
'CHLAMYDIA CULTURE','CMV CULTURE','Cmv culture disc4/21',"CMV PANEL (IGG & IGM)(LEX VA)Dc'd","COCCIDIODES AG (Dc'd 9/2019)",
'COMPREHENSIVE METABOLIC PANEL','COMPREHENSIVE VIRAL CULTURE','CRE SCREEN','Cryptococcus Ag','CRYPTOSPORIDIUM','CRYPTOSPORIDIUM/CYCLOSPORA/ISOSPORA',
'CULTURE (BODY FLUID) W/GRAM STAIN','CULTURE,TRANSFUSION REACTION','CULTURE/SUSCEPTIBILITY-URINE','CYTOMEGALOVIRUS','CYTOMEGALOVIRUS CULTURE',
'DOXYcycline INJ ','ENTEROVIRUS BY PCR','Exudate  C&S','FECAL LEUKOCYTES','FILARIA SMEAR','FLUID IN BLOOD CULTURE BOTTLES C & S','Fungal Culture  BAL',
'FUNGAL CULTURE WITH FUNGIFLUOR','FUNGAL IDENTIFICATION','FUNGAL SMEAR','FUNGAL STAIN','FUNGITELL','FUNGUS CULTURE (60149)','FUNGUS CULTURE, Other Sites',
'FUNGUS CULTURE, Sterile Body Fluids','G-6-PD SCREEN','GRAM STAIN (DONE IN HOUSE)','GRAM STAIN (V2)','GRAM STAIN OF POSITIVE BLOOD CULTURE',
'GRAM STAIN ORGANISM - POSITIVE CULTURE','HELICOBACTER PYLORI (...4/2014)*CI',"HELICOBACTER PYLORI,IGG AB(Dc'd 12/2013)",'Herpes culture disc4/21',
'HERPES CULTURE W/TYPING',"HERPES SIMPLEX AB VIRUS PNL(LEX)Dc'd",'HERPES SIMPLEX ENCEPHALITIS BY PCR (UM)','HERPES, VIRAL CULTURE',
"HISTOPLASMOSIS AG MIRA(Dc'd 9/2019)",'HODGE TEST','INFLUENZA A+B QUICKFLU','INFLUENZA VIRUS CULTURE','INSULIN HUMAN REGULAR INJ ','KOH FUNGAL PREP',
'KOH FUNGAL PREP*','KOH PREP','LC-AFB CULTURE/SMEAR/SUSCEPT (183764)','LEGIONELLA CULTURE  ','LEGIONELLA CULTURE (V2)','LEGIONELLA PNEUMOPHILA DFA',
'MAGNESIUM','MALARIA SMEAR (DCD 8/2017)','MALARIA SMEAR (NEW)','MALARIA SMEAR (PRIOR TO 12/16/15)','MALARIA SMEAR BLOOD (STL)','MALARIA SMEAR(d/c 12/2017)',
'MALARIA SMEAR*IA','MIC','MISC CULTURE & GRAM STAIN','MISCELLANEOUS MICRO TEST','MMC CULTURE,SWAB (ENDED 10/2020)','MRSA-BC (DNA)',
'MRSA/SA BLOOD CULTURE DNA (D/C 10/6/21)',"MYCOBACT. TUBERCULOSIS NAA(DC'D 1/1/17)",'MYCOBACTERIUM AVIUM PCR','MYCOLOGY C&S/SMEAR (BU)',
'MYCOLOGY CULTURE (MILW)','MYCOLOGY SMEAR  (STL)','MYCOLOGY SMEAR (FUNGUS SMEAR)','MYCOLOGY SMEAR (OTHER)','MYCOPLASMA CULTURE',
'MYCOPLASMA CULTURE (MAILOUT)',"MYCOPLASMA PANEL (IGG & IGM)Dc'd",'MYCOPLASMA PNEUMONIAE CULTURE','ORGANISM ANAEROBIC ID','ORGANISM ID 1 - ANAEROBE (BACT/YEAST)',
'ORGANISM ID 2 - AEROBIC (BACT/YEAST)','ORGANISM IDENTIFICATION','PARAINFLUENZA 1,2,3 DFA','PARASITE EXAM*','PARASITE EXAM, BLOOD(d/c 07/17)',
'PLEURAL GRAM STAIN','PROCALCITONIN (BH/SY/BU/Q)',"RAPID FLU A/B SCREEN(dc'd 080114)","RAPID RSV SCREEN(dc'd 090216)",'RESPIRATORY CULTURE PANEL',
'S&W BLOOD FUNGAL CULTURE',"SERUM CMV IgM (dc'd)",'SET 2 BLOOD CULTURE X2','SPECIAL PARASITOLOGY EXAM','SPUTUM CULTURE & SUSCEPTIBILITY',
'SPUTUM/RESPIRATORY CULTURE','SURVEILLANCE CULTURE','SUSCEPTIBILITY MIC X2','TB NUCLEIC ACID AMPLIFICATION','THROAT CULTURE',
'TIME TO DETECT-AER disc 6/9','TOXOCARA TITER','URINE BLOOD','URINE C&S','URINE C&S (CLEAN CATCH)','VANCOMYCIN RESISTANT ENTEROCOCCUS',
'VIRAL CULTURE (D/C 12/13)','VIRAL CULTURE (REFERENCE LAB)','VIRAL CULTURE(Dced 11.17.16','VIRAL CULTURE(PRIOR TO 12-18-14)','VIRAL CULTURE, HERPES',
"VIRAL CULTURE,GENERAL (DC'D 1/1/17)",'VIRAL NON-RESPIRATORY CULTURE ','VIRAL PCR ASSAY','VIROLOGY RAPID CULTURE','VIROLOGY SPECIAL PROCEDURE',
'WEST NILE VIRUS (IgG & IgM)','WOUND CULTURE','WOUND CULTURE(C&S)','YERSINIA CULTURE','zANAEROBIC CULTURE','ZBLOOD CULTURE SET','zHISTOPLASMA AG',
"ZINFLUENZA PCR AMPLIFICATION(d'cd11415)",'ZROUTINE CULTURE/BLOOD','zz C & S','ZZCMV CULTURE (AL/BH/CN/SY<5/16/13)','ZZCOCCIDIOIDES ID W/REFLEX CF',
'ZZCULT. & SUSCEPTIBILITY(MA)','ZZMALARIA SMEAR Retired 9/10/2018','ZZQ-FEVER ANTIBODIES','ZZTOXOPLASMOSIS','ZZVIRAL CULT-COMPREHENSIVE (V2<9/24/13)',
'ZZYEAST IDENTIFICATION','ZZZ LEGIONELLA CULTURE ','ZZZMALARIA SMEAR(TO 12/15/15)') then delete;

run;
/*NOTE: There were 1440274 observations read from the data set WORK.BC.*/
/*NOTE: The data set WORK.BC_V2 has 1437136 observations and 25 variables.*/









